In [1]:
#Numpy is used for data analysis

In [3]:
# numerical python to deal with numerical data 
# numpy is 3rd party library it does not belong to official python group not present in docs.python.org
# it works with homogenious data,
#it is a open source,
#easy to use,
#good performance(fast),
#used in engineering and science

In [5]:
# pip is a software which helps installing python libraries
#pip install numpy
#import numpy

In [6]:
#list supports heterogenious data but numpy supports homogenious only

In [7]:
# numpy array -- multidimentional array as _ndarray

In [8]:
import numpy as np
arr1=np.array([1,2,3,4])

In [9]:
# array is a function that to create a array

In [10]:
print(arr1)

[1 2 3 4]


In [11]:
print(type(arr1))

<class 'numpy.ndarray'>


In [12]:
print(arr1.dtype)

int32


In [13]:
print(arr1.ndim)

1


In [14]:
print(arr1.shape)

(4,)


In [15]:
print(arr1.size)

4


In [16]:
print(len(arr1))

4


In [17]:
l2=[[1,2,3],[1,2,3]]

In [18]:
arr2=np.array(l2)

In [19]:
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
print(type(arr2))

<class 'numpy.ndarray'>


In [21]:
print(arr2.dtype)

int32


In [22]:
print(arr2.ndim)

2


In [23]:
print(arr2.shape)

(2, 3)


In [24]:
print(arr2.size)

6


In [25]:
print(len(arr2))

2


In [27]:
l3=[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]

In [28]:
print(l3)

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]


In [29]:
print(type(l3))

<class 'list'>


In [30]:
arr3=np.array(l3)

In [31]:
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [33]:
print(type(arr3))

<class 'numpy.ndarray'>


In [34]:
print(arr3.dtype)

int32


In [35]:
print(arr3.ndim)

3


In [36]:
print(arr3.shape)

(2, 2, 3)


In [37]:
print(arr3.size)

12


In [38]:
import pickle

In [39]:
with open('stru_file','wb') as fh:
    con=eval(input('Enter array'))
    pickle.dump(con,fh)

Enter array [[1,2,3],[2,3,4]]


In [40]:
with open('stru_file','rb') as fh:
    con0=pickle.load(fh)

print(con)

[[1, 2, 3], [2, 3, 4]]


In [41]:
print(type(con))

<class 'list'>


In [42]:
#here in python it is list only if we want to convert to array we need to use numpy library

In [48]:
con+10

TypeError: can only concatenate list (not "int") to list

In [46]:
#here to add 10 to all elements of array

arr4=np.array(con)

In [47]:
10+arr4

array([[11, 12, 13],
       [12, 13, 14]])

In [49]:
# if you want to add all elements by 10 for a list you can use comprehension or map function

In [54]:
# using list

def my_fun(x):
    return x+10
print(con)
y=map(my_fun,[1,3,4,5])


print(list(y))

[[1, 2, 3], [2, 3, 4]]
[11, 13, 14, 15]


In [58]:
# using list

def my_fun(x):
    return x+10
# print(con)
l1=[1,2,3,4]
y=map(my_fun,l1)


print(list(y))

[11, 12, 13, 14]


In [61]:
# for arrays

In [62]:
arr1=np.array(l1)

In [63]:
arr1*2

array([2, 4, 6, 8])

In [64]:
arr1+2

array([3, 4, 5, 6])

In [65]:
arr1/2

array([0.5, 1. , 1.5, 2. ])

In [66]:
arr1%2

array([1, 0, 1, 0], dtype=int32)

In [67]:
arr1//2

array([0, 1, 1, 2], dtype=int32)

In [68]:
list(arr1/2==0)

[False, False, False, False]

In [71]:
# arange is used to arange start, end, step


arr2=np.arange(10,20,2)

In [72]:
arr2

array([10, 12, 14, 16, 18])

In [73]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [74]:
arr4=np.arange(0,11,1)

In [75]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
# dates using array
# need to check this
date1=np.arange('2023-11-01','2023-12-01',1,dtype='datetime64[D]')

In [97]:
date1

array(['2023-11-01', '2023-11-02', '2023-11-03', '2023-11-04',
       '2023-11-05', '2023-11-06', '2023-11-07', '2023-11-08',
       '2023-11-09', '2023-11-10', '2023-11-11', '2023-11-12',
       '2023-11-13', '2023-11-14', '2023-11-15', '2023-11-16',
       '2023-11-17', '2023-11-18', '2023-11-19', '2023-11-20',
       '2023-11-21', '2023-11-22', '2023-11-23', '2023-11-24',
       '2023-11-25', '2023-11-26', '2023-11-27', '2023-11-28',
       '2023-11-29', '2023-11-30'], dtype='datetime64[D]')

In [98]:
np.array(range(10,20,2))

array([10, 12, 14, 16, 18])

In [99]:

# We will not be able to give float in under python range
np.array(range(10,20,.5))

TypeError: 'float' object cannot be interpreted as an integer

In [100]:
range(10,20,.5)

TypeError: 'float' object cannot be interpreted as an integer

In [103]:
# but we can use arange function in numpy to get the required array of floating number difference

np.arange(10,20,.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [108]:
# if we use floating point number for step than we will get data in form of 10. or 111. ext

arr1=np.arange(10,20,5.5)

print(type(arr1))
print(arr1.dtype)

<class 'numpy.ndarray'>
float64


In [109]:
# but if we use step with int number will get in int form 10, and 20 ext
arr1=np.arange(10,20,1)


print(type(arr1))
print(arr1.dtype)

<class 'numpy.ndarray'>
int32


In [116]:
# using numpy arange to print datatime64 in month wise

arr1=np.arange('2023-01-01','2024-01-01',1,dtype='datetime64[M]')

print(arr1)

a=list(arr1)

print('--------------------------------------------------------------------------')
print(a)

['2023-01' '2023-02' '2023-03' '2023-04' '2023-05' '2023-06' '2023-07'
 '2023-08' '2023-09' '2023-10' '2023-11' '2023-12']
--------------------------------------------------------------------------
[numpy.datetime64('2023-01'), numpy.datetime64('2023-02'), numpy.datetime64('2023-03'), numpy.datetime64('2023-04'), numpy.datetime64('2023-05'), numpy.datetime64('2023-06'), numpy.datetime64('2023-07'), numpy.datetime64('2023-08'), numpy.datetime64('2023-09'), numpy.datetime64('2023-10'), numpy.datetime64('2023-11'), numpy.datetime64('2023-12')]


In [117]:


arr1=np.arange('2023-01-01','2024-01-01',1)

print(arr1)


TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [118]:
# print year using arange in numpy python

In [120]:
arr1=np.arange('2011','2024',1,dtype='datetime64[Y]')

In [123]:
print(arr1)

['2011' '2012' '2013' '2014' '2015' '2016' '2017' '2018' '2019' '2020'
 '2021' '2022' '2023']


In [126]:
arr1=np.arange('2011-01-01T00:00:00','2011-01-01T10:00:00',1,dtype='datetime64[h]')

In [133]:
print(arr1)

['2011-01-01T00' '2011-01-01T01' '2011-01-01T02' '2011-01-01T03'
 '2011-01-01T04' '2011-01-01T05' '2011-01-01T06' '2011-01-01T07'
 '2011-01-01T08' '2011-01-01T09']


In [134]:
for i in arr1:
    print(i)

2011-01-01T00
2011-01-01T01
2011-01-01T02
2011-01-01T03
2011-01-01T04
2011-01-01T05
2011-01-01T06
2011-01-01T07
2011-01-01T08
2011-01-01T09


In [135]:
for i in list(arr1):
    print(i)

2011-01-01T00
2011-01-01T01
2011-01-01T02
2011-01-01T03
2011-01-01T04
2011-01-01T05
2011-01-01T06
2011-01-01T07
2011-01-01T08
2011-01-01T09


In [138]:
list(arr1)

[numpy.datetime64('2011-01-01T00','h'),
 numpy.datetime64('2011-01-01T01','h'),
 numpy.datetime64('2011-01-01T02','h'),
 numpy.datetime64('2011-01-01T03','h'),
 numpy.datetime64('2011-01-01T04','h'),
 numpy.datetime64('2011-01-01T05','h'),
 numpy.datetime64('2011-01-01T06','h'),
 numpy.datetime64('2011-01-01T07','h'),
 numpy.datetime64('2011-01-01T08','h'),
 numpy.datetime64('2011-01-01T09','h')]

In [137]:
print(list(arr1))

[numpy.datetime64('2011-01-01T00','h'), numpy.datetime64('2011-01-01T01','h'), numpy.datetime64('2011-01-01T02','h'), numpy.datetime64('2011-01-01T03','h'), numpy.datetime64('2011-01-01T04','h'), numpy.datetime64('2011-01-01T05','h'), numpy.datetime64('2011-01-01T06','h'), numpy.datetime64('2011-01-01T07','h'), numpy.datetime64('2011-01-01T08','h'), numpy.datetime64('2011-01-01T09','h')]


In [128]:
# to put datetime data into a file

In [129]:
import pickle

with open('datetime.txt','wb') as fh:
    pickle.dump(arr1,fh)

In [132]:
with open('datetime.txt','rb') as fh:
    con=pickle.load(fh)


print(con)

print("------------------------------------")


for i in con:
    print(i)

['2011-01-01T00' '2011-01-01T01' '2011-01-01T02' '2011-01-01T03'
 '2011-01-01T04' '2011-01-01T05' '2011-01-01T06' '2011-01-01T07'
 '2011-01-01T08' '2011-01-01T09']
------------------------------------
2011-01-01T00
2011-01-01T01
2011-01-01T02
2011-01-01T03
2011-01-01T04
2011-01-01T05
2011-01-01T06
2011-01-01T07
2011-01-01T08
2011-01-01T09


In [139]:
# to check processing of list and arry

In [143]:
%time l1=list(range(1,10000000))

CPU times: total: 844 ms
Wall time: 1.09 s


In [144]:
%time arr1=np.arange(1,10000000)

CPU times: total: 31.2 ms
Wall time: 45 ms


In [145]:
# convert data homogenious 

l3=[1,2,'hello']

arr3=np.array(l3)

In [146]:
arr3

array(['1', '2', 'hello'], dtype='<U11')

In [147]:
arr3.dtype

dtype('<U11')

In [148]:
print(type(arr3))

<class 'numpy.ndarray'>


In [149]:
# random package: - To create an array of random data
a4=np.random.randint(10,20,(10))

In [150]:
print(a4)

[12 17 19 18 16 15 12 16 17 18]


In [157]:
a5=np.random.randint(10,20,(20,3))

In [158]:
print(a5)

[[12 10 16]
 [10 14 10]
 [19 17 18]
 [17 19 13]
 [16 17 15]
 [13 11 14]
 [19 10 11]
 [10 15 10]
 [14 12 13]
 [19 17 10]
 [10 13 16]
 [17 13 15]
 [17 14 12]
 [14 17 12]
 [19 11 15]
 [18 19 10]
 [11 12 16]
 [13 10 15]
 [17 14 10]
 [17 11 16]]


In [159]:
a5=np.random.randint(10,20,(20,3,2))

In [160]:
print(a5)

[[[13 15]
  [17 14]
  [19 18]]

 [[18 10]
  [18 19]
  [12 12]]

 [[13 17]
  [18 10]
  [14 17]]

 [[17 17]
  [15 11]
  [13 19]]

 [[11 16]
  [13 15]
  [18 17]]

 [[14 19]
  [12 16]
  [13 16]]

 [[19 11]
  [15 19]
  [12 16]]

 [[11 10]
  [12 14]
  [17 13]]

 [[12 10]
  [11 18]
  [19 16]]

 [[10 15]
  [18 15]
  [17 12]]

 [[14 15]
  [19 13]
  [10 10]]

 [[10 19]
  [11 12]
  [14 10]]

 [[16 17]
  [10 14]
  [10 10]]

 [[11 18]
  [12 18]
  [14 12]]

 [[14 17]
  [12 16]
  [19 15]]

 [[16 10]
  [16 14]
  [18 13]]

 [[19 17]
  [12 13]
  [10 14]]

 [[16 14]
  [19 10]
  [12 14]]

 [[10 19]
  [18 12]
  [19 19]]

 [[17 12]
  [12 12]
  [14 19]]]


In [161]:
# creating an array b/w 0 and 1

In [162]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)

    Random values in a given shape.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.

    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.

    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.

    See Also
    --------
    random

    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618

In [165]:
arr4=np.random.rand(1,2)
# above one row two column

# b/w zero and 1 

In [166]:
print(arr4)

[[0.260158   0.08777516]]


In [167]:
ar5=np.random.randn(2,2)

In [168]:
print(ar5)

[[ 1.03526814 -0.41866036]
 [ 1.99971922 -1.76185446]]


In [169]:
# zeros

# default dtype is float
z1=np.zeros((3,4))

print(z1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [170]:
print(z1.dtype)

float64


In [172]:
z1=np.zeros((3,4),dtype='int32')

In [173]:
print(z1.dtype)

int32


In [174]:
print(z1.shape)

(3, 4)


In [175]:
print(z1.size)

12


In [176]:
print(z1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [180]:
# for ones
# default is floar
one1=np.ones((1,4))

In [181]:
print(one1)

[[1. 1. 1. 1.]]


In [182]:
one1=np.ones((1,4),dtype='int32')

In [183]:
print(one1)

[[1 1 1 1]]


In [184]:
# if you want to fill with specific data to array you can use full

anyN=np.full((10,),12)

print(anyN)

[12 12 12 12 12 12 12 12 12 12]


In [185]:
anyN=np.full((10,),1.4)

In [186]:
print(anyN)

[1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4]


In [187]:
# as we can do arithmatica operation on array as zero is default float

In [189]:
arr1=(np.zeros((10,),dtype='int32'))+2

In [190]:
print(arr1)

[2 2 2 2 2 2 2 2 2 2]


In [193]:
# multiplication

arr1=(np.full((10,),2,dtype='int32'))+2

In [194]:
print(arr1)

[4 4 4 4 4 4 4 4 4 4]


In [195]:
# matrix that is 2d array

# identity(): is a square matrix (rows == columns) whose diagonal are 1 rest are 0

In [196]:
ide1=np.identity(3)

In [197]:
print(ide1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [198]:
ide1=np.identity(3,dtype='int32')

In [199]:
print(ide1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [200]:
# eye function
# help np.eye but default is float
e1=np.eye(3,3,k=0,dtype='int32')

In [201]:
print(e1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [202]:
# here k means dialgonal if k==0
# if k =1 than 1 up from diagonal
# if k=-1 means one down from diagonal



In [203]:
e2=np.eye(3,3,k=1,dtype='int32')

print(e2)

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [204]:
e3=np.eye(3,3,k=-1,dtype='int32')

In [205]:
print(e3)

[[0 0 0]
 [1 0 0]
 [0 1 0]]


In [209]:
# k=0 main diagonal

i1=np.identity((4,3),k=10,dtype='int32')

TypeError: identity() got an unexpected keyword argument 'k'

In [210]:
# diagonal elements
# Fetal diagonal elements 

arr1=np.random.randint(1,10,(3,3))

print(arr1)

[[8 5 1]
 [9 3 8]
 [3 7 4]]


In [212]:
d1=np.diag(arr1,k=0)

print(d1)

[8 3 4]


In [213]:
# all() and any() in python


print(arr1)

[[8 5 1]
 [9 3 8]
 [3 7 4]]


In [214]:
print(np.all(arr1))

True


In [215]:
print(np.any(arr1))

True


In [217]:
# first row elemenets

print(np.all(arr1,1))

[ True  True  True]


In [218]:
# if all we apply any one is zero we will get false

In [220]:
arr1=np.random.randint(0,10,(3,3))

In [221]:
arr1

array([[8, 5, 0],
       [9, 2, 1],
       [0, 6, 3]])

In [222]:
print(np.all(arr1,1))

[False  True False]


In [223]:
print(np.all(arr1))

False


In [225]:
print(np.any(arr1))

# if any one element is non zero we will get true

True


In [226]:
print(np.any(arr1))

# axis=1 for row axis=0 for column

True


In [228]:
print(np.any(arr1,axis=1))

[ True  True  True]


In [229]:
print(np.any(arr1,axis=1))

[ True  True  True]


In [230]:
# brodcasting: - applieng operation on 2 or more arrays

arr1=np.random.randint(0,10,(5,))

print(arr1)

[3 2 6 9 1]


In [243]:
arr2=np.random.randint(1,10,(5,))
print(arr2)

[6 4 2 3 1]


In [232]:
print(arr1+arr2)

[ 6  5  9 14  6]


In [234]:
# operands could not broadcast together with shape 5 or 4 or with different shape

In [245]:
arr3=np.random.randint(1,10,(4,))
print(arr3)

[4 2 9 1]


In [246]:
print(arr1+arr3)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [237]:
# we can perform any arithmatic operation on any array unless it is not having diff shape

In [247]:
# this cannot be done on lists

a=[1,0,1]
b=[2,0,1]

a/b

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [240]:
# we have function for broadcasting

In [248]:
print(np.add(arr1,arr2))

[ 9  6  8 12  2]


In [249]:
print(np.subtract(arr1,arr2))

[-3 -2  4  6  0]


In [250]:
print(np.multiply(arr1,arr2))

[18  8 12 27  1]


In [251]:
print(np.divide(arr1,arr2))

[0.5 0.5 3.  3.  1. ]


In [254]:
# comparision we can do for arrays

print(arr1 > arr2)

[False False  True  True False]


In [255]:
# we cant apply logical operators on arrays

print(arr1 and arr2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [256]:
print(arr1 or arr2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [257]:
# matrix

In [258]:
m1=np.random.randint(1,10,(3,3))

In [259]:
print(m1)

[[4 5 1]
 [9 8 9]
 [4 2 1]]


In [260]:
m2=np.random.randint(1,10,(3,3))

In [261]:
print(m2)

[[6 8 3]
 [5 4 8]
 [9 8 1]]


In [263]:
print(np.multiply(m1,m2))

[[24 40  3]
 [45 32 72]
 [36 16  1]]


In [264]:
print(m1*m2)

[[24 40  3]
 [45 32 72]
 [36 16  1]]


In [266]:
# @ means dot product

# no of rows of first matrix = no of columns of 2nd matrix
# shape of new matrix will be no of rows of 1st matrix and no of columns of 2nd matrix

In [267]:
print(m1@m2)

[[ 58  60  53]
 [175 176 100]
 [ 43  48  29]]


In [268]:
print(np.dot(m1,m2))

[[ 58  60  53]
 [175 176 100]
 [ 43  48  29]]


In [269]:
# transpose of matrix: here columns became rows and rows became columns

In [270]:
# some statistical functions on matrix

In [271]:
arr1=np.random.randint(1,10,(6))

In [272]:
print(arr1)

[4 5 2 3 2 5]


In [273]:
print(np.mean(arr1))

3.5


In [274]:
print(np.median(arr1))

3.5


In [288]:
print(np.mode(arr1))
# it gives error because mode is categorical data

AttributeError: module 'numpy' has no attribute 'mode'

In [278]:
print(np.modf(arr1))

(array([0., 0., 0., 0., 0., 0.]), array([4., 5., 2., 3., 2., 5.]))


In [279]:
print(np.std(arr1))

1.2583057392117916


In [280]:
print(np.var(arr1))

1.5833333333333333


In [283]:
# var is square of std

st=np.std(arr1)
var=np.var(arr1)

In [284]:
print(st==var)

False


In [286]:
print(st*st==var)

True


In [289]:
# indexing and slicing

print(arr1[0])

4


In [290]:
print(arr1[2])

2


In [291]:
print(arr1[0:])

[4 5 2 3 2 5]


In [292]:
print(arr1)

[4 5 2 3 2 5]


In [293]:
print(arr1[::-1])

[5 2 3 2 5 4]


In [295]:
print(arr1[-1::-1])

[5 2 3 2 5 4]


In [296]:
print(arr1[-1::])

[5]


In [297]:
print(arr1[:-1:])

[4 5 2 3 2]


In [298]:
# array are mutable

In [299]:
print(id(arr1))

2572239827472


In [300]:
arr1

array([4, 5, 2, 3, 2, 5])

In [301]:
arr1[0]=6

In [302]:
print(arr1)

[6 5 2 3 2 5]


In [303]:
print(id(arr1))

2572239827472


In [304]:
# as no change in id so it is mutable

In [305]:
arr1[0:2:1]=-1

In [306]:
arr1

array([-1, -1,  2,  3,  2,  5])

In [308]:
arr1[0:2:]=20,30

In [309]:
arr1

array([20, 30,  2,  3,  2,  5])

In [310]:
print(arr1)

[20 30  2  3  2  5]


In [311]:
# view 

slice1=arr1[2:5]

print(slice1)

[2 3 2]


In [312]:
print(type(slice1))

<class 'numpy.ndarray'>


In [313]:
print(slice1.dtype)

int32


In [314]:
slice1[0]=900

In [315]:
print(arr1)

[ 20  30 900   3   2   5]


In [316]:
# hence slice1 is taken from arr1, hence it is a part of that, so if you change in slice1 arr1 corresponding element will change

In [317]:
# slice shares same memory loc hence this is not there in lists

In [318]:
# but memory address will be different for slice and array

In [319]:
m1=np.random.randint(1,10,(3,3))

print(m1)

[[5 3 8]
 [5 1 6]
 [9 3 1]]


In [320]:
m1[0][0]

5

In [321]:
m1=np.random.randint(1,10,(3,4))

In [322]:
print(m1)

[[8 5 9 5]
 [7 7 5 2]
 [3 9 2 3]]


In [327]:
slice1=m1[0:2,2:4]

In [328]:
print(slice1)

[[9 5]
 [5 2]]


In [329]:
# here last element will be excluded

In [330]:
slice1[0,0]=-100

In [331]:
print(slice1)

[[-100    5]
 [   5    2]]


In [332]:
print(m1)

[[   8    5 -100    5]
 [   7    7    5    2]
 [   3    9    2    3]]


In [333]:
# so basically in array if you change value in slice data will change in array also

In [335]:
# arithmatica progression:- elements are evenly spaced from each other

In [338]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [340]:
# geometrical progression
np.geomspace(1,20,10)

array([ 1.        ,  1.39495079,  1.94588772,  2.71441762,  3.78647901,
        5.2819519 ,  7.368063  , 10.27808533, 14.33742329, 20.        ])

In [341]:
# reshape

arr1=np.random.randint(1,10,(4,5))

In [342]:
print(arr1)

[[4 4 1 5 9]
 [5 5 8 7 9]
 [4 2 4 9 2]
 [2 4 3 5 8]]


In [343]:
print(np.reshape(arr1,(5,4)))

[[4 4 1 5]
 [9 5 5 8]
 [7 9 4 2]
 [4 9 2 2]
 [4 3 5 8]]


In [344]:
# for reshape you need to have same size both in original and in reshaped one

In [345]:
# size=product(shape)

In [346]:
# cancatination of an array

arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(2,3))

In [350]:
print(arr1)

[[2 6 9]
 [7 4 4]]


In [351]:
print(arr2)

[[8 7 9]
 [7 2 2]]


In [349]:
print(np.concatenate([arr1,arr2]))

[[2 6 9]
 [7 4 4]
 [8 7 9]
 [7 2 2]]


In [353]:
print(np.concatenate([arr1,arr2],axis=1))

[[2 6 9 8 7 9]
 [7 4 4 7 2 2]]


In [354]:
# splitting of an array

In [357]:
arr1=np.random.randint(1,10,(8,))

In [358]:
print(arr1)

[7 3 1 2 3 1 6 8]


In [368]:
np.split(3)
# here np.split only for equally splitting array with number

TypeError: split() missing 1 required positional argument: 'indices_or_sections'

In [360]:
np.split(arr1,4)

[array([7, 3]), array([1, 2]), array([3, 1]), array([6, 8])]

In [359]:
# for unequal splits

In [361]:
a,b,c=np.array_split(arr1,3)

In [363]:
print(arr1)

[7 3 1 2 3 1 6 8]


In [362]:
print(a)

[7 3 1]


In [364]:
print(b)

[2 3 1]


In [365]:
print(c)

[6 8]
