In [67]:
# Pandas: - Python library that provides data structure and methods to work with structured or tabular data, data in fast or easy way
# pandas internally uses numpy

In [68]:
# pandas 3rd party library is fast, flexible, powerfull and easy to use open source data analysis and manipulation tool, built on top of the python program

In [69]:
'''pandas supports the integration with many file formats or data sources out of the box(csv, excel, sql, json, parquet) and converts into dataframe 
vice-versa'''

'pandas supports the integration with many file formats or data sources out of the box(csv, excel, sql, json, parquet) and converts into dataframe \nvice-versa'

In [70]:
import pandas as pd

In [71]:
ser1=pd.Series([10,20,30])

In [72]:
print(ser1)

0    10
1    20
2    30
dtype: int64


In [73]:
print(type(ser1))

<class 'pandas.core.series.Series'>


In [74]:
print(ser1.dtype)

int64


In [43]:
print(ser1.index)

RangeIndex(start=0, stop=3, step=1)


In [44]:
i1=ser1.index

In [45]:
print(type(i1))

<class 'pandas.core.indexes.range.RangeIndex'>


In [46]:
v1=ser1.values

In [47]:
print(v1)

[10 20 30]


In [48]:
print(type(v1))

<class 'numpy.ndarray'>


In [49]:
# hence pandas use numpy internally

In [50]:
# we can give indexing by mentioning under index

In [51]:
ser2=pd.Series([10,20,30,40],index=[1,2,3,4])

In [52]:
print(ser2)

1    10
2    20
3    30
4    40
dtype: int64


In [53]:
ser3=pd.Series(range(10,60,10),index=range(1,6,1))

In [54]:
print(ser3)

1    10
2    20
3    30
4    40
5    50
dtype: int64


In [55]:
v2=ser2.values

In [56]:
print(v2)

[10 20 30 40]


In [57]:
v3=ser3.values

In [58]:
print(v3)

[10 20 30 40 50]


In [59]:
# here we started index by 1 so 
print(ser3[1])

10


In [60]:
print(ser3[3])

30


In [61]:
ser4=pd.Series(range(10,40,10),index=['a','b','c'])

In [62]:
ser4

a    10
b    20
c    30
dtype: int64

In [63]:
# to fetch data using inner index we have an option called as loc and iloc

In [64]:
# iloc-inner index
# loc-outer index

print(ser3)

1    10
2    20
3    30
4    40
5    50
dtype: int64


In [65]:
ser3.iloc[0]

10

In [76]:
ser3.loc[0]

KeyError: 0

In [77]:
# we need to give exactly same number of index points to store

In [78]:
ser5=pd.Series(range(10,60,10),index=range(1,3,1))

ValueError: Length of values (5) does not match length of index (2)

In [ ]:
# length of the series should be equal to length of the indexes

In [92]:
ser6=pd.Series([10,20,30], index=['Naveen','Veeresh','Shetter'])

In [93]:
print(ser6)

Naveen     10
Veeresh    20
Shetter    30
dtype: int64


In [94]:
ser7=pd.Series([10,20,30], index=['Naveen','Naveen','Naveen'])

In [95]:
print(ser7)

Naveen    10
Naveen    20
Naveen    30
dtype: int64


In [96]:
# Series are mutable

In [97]:
ser6.loc['Naveen']=89

In [98]:
print(ser6)

Naveen     89
Veeresh    20
Shetter    30
dtype: int64


In [99]:
ser7.loc['Naveen'].iloc[-1]=44

C:\Users\Skyline Solutions\AppData\Local\Temp\ipykernel_7084\3176042359.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ser7.loc['Naveen'].iloc[-1]=44


In [100]:
print(ser7)

Naveen    10
Naveen    20
Naveen    44
dtype: int64


In [101]:
# to add or we call this operations as broadcasting(means parallel operation)

In [102]:
print(ser6+1)

Naveen     90
Veeresh    21
Shetter    31
dtype: int64


In [103]:
print(ser6)

Naveen     89
Veeresh    20
Shetter    30
dtype: int64


In [104]:
# get whose marks are greater than 100

In [105]:
ser6>100

Naveen     False
Veeresh    False
Shetter    False
dtype: bool

In [106]:
ser6>67

Naveen      True
Veeresh    False
Shetter    False
dtype: bool

In [107]:
ser6[ser6>80]

Naveen    89
dtype: int64

In [108]:
import numpy as np

ser7=pd.Series(np.random.randint(1,10,5))

In [109]:
print(ser7)

0    1
1    8
2    4
3    1
4    8
dtype: int32


In [110]:
# to print even numbers in series

ser7[ser7%2==0]

1    8
2    4
4    8
dtype: int32

In [111]:
print(ser7.loc[1])

8


In [112]:
print(ser7.loc[1::])

1    8
2    4
3    1
4    8
dtype: int32


In [113]:
# creating series using addict

matches_won={'IN':9,'PAK':4,'SA':7,'ENG':3,'AFG':4}

print(matches_won)

{'IN': 9, 'PAK': 4, 'SA': 7, 'ENG': 3, 'AFG': 4}


In [114]:
s1=pd.Series(matches_won)

In [115]:
print(s1)

IN     9
PAK    4
SA     7
ENG    3
AFG    4
dtype: int64


In [116]:
# NAN is a value used to represent a missing value in both pd and np

In [117]:
ser9=pd.Series(matches_won)

In [118]:
print(ser9)

IN     9
PAK    4
SA     7
ENG    3
AFG    4
dtype: int64


In [119]:
print(ser9.index)

Index(['IN', 'PAK', 'SA', 'ENG', 'AFG'], dtype='object')


In [120]:
print(ser9.value_counts)

<bound method IndexOpsMixin.value_counts of IN     9
PAK    4
SA     7
ENG    3
AFG    4
dtype: int64>


In [121]:
print(ser9.values)

[9 4 7 3 4]


In [122]:

ser9=pd.Series(matches_won,index=['PAK','SA','BR'])

In [123]:
print(ser9)

PAK    4.0
SA     7.0
BR     NaN
dtype: float64


In [124]:
print(type(ser9))

<class 'pandas.core.series.Series'>


In [125]:
print(ser9.dtype)

float64


In [126]:
ser10=pd.Series([10,20,30,'H'])

In [127]:
ser10

0    10
1    20
2    30
3     H
dtype: object

In [128]:
print(type(ser10))

<class 'pandas.core.series.Series'>


In [129]:
ser11=pd.Series({'nov':90,'ver':96})

In [130]:
print(ser11)

nov    90
ver    96
dtype: int64


In [131]:
ser12=pd.Series({'nov':89,'ver':96})

In [132]:
print(ser12)

nov    89
ver    96
dtype: int64


In [133]:
# we can add or do any arithmatic operation like

print(ser11+ser12)

nov    179
ver    192
dtype: int64


In [134]:
total=ser11+ser12

In [ ]:
print(total)

In [ ]:
print(type(total))

In [ ]:
print(total.isnull())

In [ ]:
print(total[total.isnull()])

In [ ]:
print(total[total.notnull()])

In [ ]:
ser11=pd.Series({'Naveen':90,'Veeresh':95,'Shetter':98})

In [ ]:
print(ser11)

In [ ]:
# ascending

In [ ]:
print(ser11.sort_values(ascending=True))

In [ ]:
print(ser11.sort_values(ascending=False))

In [ ]:
# dataframes

In [ ]:
data1={'name':['Naveen','Veeresh','Shetter'],'marks':[10,20,30],'age':[20,19,90]}

In [ ]:
print(data1)

In [ ]:
df1=pd.DataFrame(data1)

In [ ]:
print(df1)

In [ ]:
print(type(df1))

In [ ]:
df1.index

In [ ]:
df1.values

In [ ]:
df1.columns

In [ ]:
# to make a dataframe all have same length

In [ ]:
df1.index

In [ ]:
df1.columns

In [ ]:
df1.values

In [ ]:
data=data1

In [ ]:
df2=pd.DataFrame(data,columns=['ids','percent','grades'])

In [ ]:
df2

In [ ]:
df2=pd.DataFrame(data,columns=['ids','percents','grades'])

In [ ]:
print(df2)

In [ ]:
df3=pd.DataFrame(data,index=data['name'],columns=['ids','percents'])

In [ ]:
df3

In [ ]:
print(data)

In [ ]:
print(type(data))

In [ ]:
print(data1)

In [ ]:
print(type(data1))

In [ ]:
df1

In [ ]:
# drop or deleting a column

In [ ]:
data={'name':['Naveen','Veeresh','Shetter'],
     'ids':[101,102,103],
     'percents':[89,90,97]}

In [ ]:
data

In [ ]:
df2=pd.DataFrame(data)

In [ ]:
print(df2)

In [ ]:
# # drop or deleting a column

In [ ]:
df2.drop(['percents'],axis=1)

In [ ]:
print(df2)

In [ ]:
# here it is not deleted completely so you need to delete by putting inplace=True

In [ ]:
df3=pd.DataFrame(data)

In [ ]:
df3

In [ ]:
df3.drop(['percents'],axis=1,inplace=True)

In [ ]:
print(df3)

In [ ]:
# now to delete a row

In [ ]:
df3.drop([0],axis=0,inplace=True)

In [ ]:
print(df3)

In [ ]:
df3['percents']=[10,20]

In [ ]:
df3

In [ ]:
df3['pe']=[10,20,30]

# here while creating, we can add directly but index length should be same

In [ ]:
df3

In [ ]:
df2

In [ ]:
df2['percents']>90

In [ ]:
df2[df2['percents']>90]

In [ ]:
df2[df2['percents']<90]

In [ ]:
df2[df2['percents']==90]

In [ ]:
arr1=np.where(df2['percents']>=90,'yes','no')

In [ ]:
arr1

In [ ]:
print(arr1)

In [ ]:
df2['good']=arr1

In [ ]:
df2

In [ ]:
df2.loc[3]=['Ling','104','100','yes']

In [ ]:
df2

In [ ]:
# the above thing can be done by

In [ ]:
def cal_grades(percent):
    if percent>=95:
        return 'A'
    else:
        return 'B'

df2['grades']=df2['percents'].apply(cal_grades)

In [ ]:
df2.drop([3],axis=0,inplace=True)

In [ ]:
df2

In [ ]:
df2.loc[3]=['Ling','104',100,'yes']

In [ ]:
df2

In [ ]:
print(type(df2['percents']))

In [ ]:
def cal_grades(percent):
    if percent>=95:
        return 'A'
    else:
        return 'B'

df2['grades']=df2['percents'].apply(cal_grades)

In [ ]:
df2

In [ ]:
df2.describe

In [ ]:
df2.describe()

In [ ]:
# 15nov

In [ ]:
data={'Company':['A','B','C','D'],
     'Year':[2019,2020,2021,2022],
     'Sales':[100,89,90,91],
     'Profits':[11,9,4,5]}

In [ ]:
df1=pd.DataFrame(data)

In [ ]:
df1

In [ ]:
df1['Year']

In [ ]:
df1.describe()

In [ ]:
df1.isnull()

In [ ]:
df1.isnull

In [ ]:
print(type(df1['Year'][0]))

In [ ]:
df1['Year']

In [ ]:
# type convertion

In [ ]:
df1.describe(include=None)

In [ ]:
df1.info()

In [ ]:
df1['Year'].astype(object)

In [ ]:
df1.info()

In [ ]:
df1['Company']

In [ ]:
df1['Year'].value_counts()

In [ ]:
df1['Profits']

In [ ]:
df1['Sales']

In [ ]:
# fetch the rows which has only company B

In [ ]:
df1['Company']=='B'

In [ ]:
df1[df1['Company']=='B']

In [ ]:
df1[df1['Sales']>=90]

In [ ]:
df1[df1['Sales']>=90]['Company']

In [ ]:
df1[df1['Sales']>=90]['Profits']

In [ ]:
df1[df1['Company']=='B']

In [ ]:
df1['Company']

In [ ]:
df1[df1['Company']=='B']

In [ ]:
df1[df1['Company']=='B']['Sales']

In [ ]:
df1[df1['Sales']>70].value_counts()

In [ ]:
df1[df1['Profits']<70]['Profits']

In [ ]:
df1[df1['Profits']<70][['Year','Company']]

In [ ]:
df1[(df1['Company']=='A') & (df1['Profits']<40)]

In [ ]:
df1[(df1['Sales']>100) | (df1['Profits']>10)]

In [ ]:
df1[df1['Profits']<40]

In [ ]:
# query

In [ ]:
df1.query("Company=='A'")

In [ ]:
df1.query("Company=='A' and Profits>30")

In [ ]:
df1.query("Company=='A' or Profits>30")

In [ ]:
# find mean of profit of company A

In [ ]:
df1[df1['Company']=='A']['Profits']

In [ ]:
df1[df1['Company']=='A']['Profits'].mean()

In [ ]:
df1['Company'].mode()

In [ ]:
df1['Company'].describe()

In [ ]:
df1.describe()

In [ ]:
df1['Year'].mode()

In [ ]:
df1['Year'].max()

In [ ]:
df1.info()

In [ ]:
df1.describe()

In [ ]:
df1['Sales'].quantile()

In [ ]:
df1['Sales'].quantile(.25)

In [ ]:
df1['Sales'].quantile(1)

In [ ]:
df1['Sales'].quantile(0.5)

In [ ]:
# pivot: - Index, column, and row

In [ ]:
pivot_df=df1.pivot(index='Company',columns='Year',values='Sales')

In [ ]:
print(pivot_df)

In [ ]:
pivot_df=df1.pivot(index='Company',columns='Year',values=['Sales','Profits'])

In [ ]:
print(pivot_df)

In [ ]:
df1